### ISSUE TITLE
중국 넣을 거 추천 받음

### ISSUE THREAD

**Issue by khg2202** [East-Asia-Flavor-Pack/East-Asia-Flavor-Pack#6]
생각나는 거 싹 적어주면 ㄳ

**Comment by khg2202** [comment]
1. 1차 2차 아편전쟁 항상 일어나게 수정
2. 태평천국 이해집단 지도자 만져서 폭동 안나게 수정 (거의 완료)
3. 회족 봉기 스코프 수정 (완료)
4. 1차 2차 사이에 유럽 국가가 중국에 덜 찝쩍이게 수정
5. 러시아의 일리 점령, 1855년 함풍황하대개도, 염군의 난 이벤트 추가
6. 태평천국이 운남 귀주 사천 중경 차지 못하게 수정 (완료)
7. 태평천국이 되도록 숙주& 절강 쪽을 차지하도록 수정 (완료라 침)
8. 중국 법안 신앙의 자유로 바꾸고 국교는 유교, 팝들도 그렇게 바꾸기 (완료)

**Comment by bighungryjames** [comment]
중국 군벌화, 국민당 공산당 서북삼마 광서군벌 (호이 군벌들): 호이가 36년 시작이고 빅토가 36년에 끝나니까 얘네들 등장 가능해야 함

**Comment by MADCAT416** [comment]
1.저널 따른 군벌 분열 한번에가 아니고 단계적+처음엔 괴뢰국~자치령으로 분열되도록 변경 ex)1차로 위구르+몽골이 자치령으로 분열 두번째로 남서부 사천,운남 군벌 등장 같은 식으로
2.강북+만주가 마지막까지 남는 지역으로 하고 최종적으로 신해혁명 이벤트로 세개 선택지 1.직예군벌(북양정부)로 플레이 2.국민정부로 플레이 3.화북은 직예정부로 독립하고 만주를 영토로 청 플레이(만주가 아직 청 영토면 등장하는 선택지로)

**Comment by bighungryjames** [comment]
아 그리고 바닐라에 서태후 없지? 서태후가 시작 시점 태자인 혁저 엄마라서 서태후가 국고 횡령해서 적자나는 이벤트 넣으면 어떨까 싶은데. ECCHI 인물추가모드에 서태후가 있어서 그거 깔든지 해서 서태후를 지주 리더로 등장시켜도 재미있을 것 같음

**Comment by khg2202** [comment]
> 아 그리고 바닐라에 서태후 없지? 서태후가 시작 시점 태자인 혁저 아내라서 서태후가 국고 횡령해서 적자나는 이벤트 넣으면 어떨까 싶은데. ECCHI 인물추가모드에 서태후가 있어서 그거 깔든지 해서 서태후를 지주 리더로 등장시켜도 재미있을 것 같음

(진행중)

**Comment by khg2202** [comment]
공장들은 정부 운영으로 바꾸던지 할것

**Comment by khg2202** [comment]
일단 끝
